# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkujJn9xHqOo15dKVzofqFsHQvpzHwEE
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# 
# # -----------------------------
# # PAGE TITLE
# # -----------------------------
# st.title("Stock Market Intelligence System")
# 
# # -----------------------------
# # SIDEBAR
# # -----------------------------
# st.sidebar.header("Asset Selection")
# 
# asset = st.sidebar.selectbox(
#     "Select Asset",
#     ["Sensex", "Reliance", "TCS", "Infosys", "HDFC Bank"]
# )
# 
# # -----------------------------
# # TABS
# # -----------------------------
# tab1, tab2, tab3 = st.tabs(
#     ["Predictions", "Chat", "Comparison"]
# )
# 
# # =============================
# # TAB 1
# # =============================
# with tab1:
# 
#     st.header("Predictions")
# 
#     st.write("Selected Asset:", asset)
# 
#     price_data = pd.DataFrame({
#         "Day":[1,2,3,4,5],
#         "Price":[100,102,101,105,108]
#     })
# 
#     st.subheader("Price Trend")
#     st.line_chart(price_data.set_index("Day"))
# 
#     st.subheader("Prediction")
#     st.success("UP")
# 
#     st.subheader("Confidence Score")
#     st.write("87%")
# 
#     st.subheader("SHAP Feature Importance")
#     st.info("SHAP Feature Importance Chart")
# 
#     st.subheader("SHAP Waterfall Plot")
#     st.info("SHAP Waterfall Plot")
# 
# # =============================
# with tab2:
# 
#     st.header("Chat")
# 
#     question = st.text_input("Ask your question")
# 
#     if "chat_history" not in st.session_state:
#         st.session_state.chat_history = []
# 
#     if st.button("Ask"):
# 
#         if question.strip():
#             answer = generate_answer(question)
#         else:
#             answer = "Please enter a question."
# 
#         st.session_state.chat_history.append(("User", question))
#         st.session_state.chat_history.append(("Assistant", answer))
# 
#     st.subheader("Chat History")
# 
#     for role, message in st.session_state.chat_history:
#         st.write(f"**{role}:** {message}")
# 
# # =============================
# # TAB 3
# # =============================
# with tab3:
# 
#     st.header("Comparison")
# 
#     comparison = pd.DataFrame({
# 
#         "Asset":[
#             "Sensex",
#             "Reliance",
#             "TCS",
#             "Infosys",
#             "HDFC Bank"
#         ],
# 
#         "Prediction":[
#             "UP",
#             "UP",
#             "DOWN",
#             "UP",
#             "DOWN"
#         ],
# 
#         "Accuracy":[
#             0.76,
#             0.81,
#             0.79,
#             0.83,
#             0.80
#         ]
# 
#     })
# 
#     st.subheader("Comparison Table")
#     st.dataframe(comparison)
# 
#     st.subheader("Bar Chart")
#     st.bar_chart(comparison.set_index("Asset")["Accuracy"])
# 
#     st.subheader("Prediction Comparison")
#     st.dataframe(comparison[["Asset","Prediction"]])